name: CI

on:
  push:
    branches: [ master, v1 ]
  pull_request:
    branches: [ master, v1 ]

jobs:
  macosx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@main
    - run: npm install
    - run: npm test
    - run: ./build.sh
    - uses: actions/upload-artifact@main
      with:
        name: alfred-emoji.alfredworkflow
        path: alfred-emoji.alfredworkflow
